import "@/styles/globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>docs lasting</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className=" bg-white dark:bg-slate-900 relative">
        <picture className="absolute top-0 dark:hidden pointer-events-none">
          <source srcSet="/images/docbg.avif" type="image/avif" />
          <img src="/images/docbg.png" alt="docbg" />
        </picture>
        <picture className="absolute top-0 dark:block hidden pointer-events-none">
          <source srcSet="/images/docbg_dark.avif" type="image/avif" />
          <img src="/images/docbg_dark.png" alt="docbg" />
        </picture>
        {children}
      </body>
    </html>
  );
}
