import "@/styles/globals.css";
import DocSearchModal from "@/ui/DocSearchModal";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>docs lasting</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className=" bg-white dark:bg-slate-900">
        <DocSearchModal />
        {children}
      </body>
    </html>
  );
}
